### ISSUE TITLE
using big.Int as backing type

### ISSUE THREAD

**Issue by bendecoste** [gorgonia/tensor#28]
Hello all!

I am wondering about the best way to go about using big.Int or big.Float as the backing type for a tensor.

```golang
data := make([]*big.Int, 4)
data[0] = big.NewInt(0)
data[1] = big.NewInt(1)
data[2] = big.NewInt(2)
data[3] = big.NewInt(3)

a := tensor.New(tensor.WithShape(2, 2), tensor.WithBacking(data))
b := tensor.New(tensor.WithShape(2, 2), tensor.WithBacking(data))
```

works fine, but you cannot do 
```golang
c, err := a.Mul(b)
```

because the type is not a member of Number.

I browsed the docs for a while and it looks like I could support this by creating an engine that implements `Muler`.  But I would have to do this for a bunch of ops I want, and again for `big.Float`.

I may be wrong but I feel like I would get a lot of this for free if I could tell tensor how two `big.Int`'s should be multiplied. e.g. `return big.NewInt(0).Mul(a,b)`

I am fairly new to golang so maybe this is a dumb question, but is there a way to do this?

Is there a more recommended way to go about this?

Thanks!

**Comment by chewxy** [comment]
> I browsed the docs for a while and it looks like I could support this by creating an engine that implements Muler.

That's the only way to.

**Comment by chewxy** [comment]
```
type BigIntEngine struct {
    tensor.StdEng
}

func (e *BigIntEngine) Mul(a, b tensor.Tensor, opts ...tensor.FuncOpt) (retVal tensor.Tensor, err error) {
swtich a.Dtype() {
    case BigInt:
        dataA := a.Data().([]*big.Int)
        dataB := b.Data().([]*big.Int)
        for i, v := range dataA {
              dataA[i] = v.Mul(dataB[i])
        }
}
}
```

**Comment by chewxy** [comment]
> I may be wrong but I feel like I would get a lot of this for free if I could tell tensor how two big.Int's should be multiplied. e.g. return big.NewInt(0).Mul(a,b)

Interesting issue you brought up. Very early versions of gorgonia supported this. It turned out tho be a bad idea because the compiler was unable to perform its optimizations dynamically. Therefore function calls became the bottleneck

**Comment by bendecoste** [comment]
Okay thanks a lot for the info!

Off-topic for this issues but I have one follow-up and then I will close this issue.  I implemented an engine that does the ops needed for my use-case.  Regarding `MatMul`, which provides a tensor you should modify.  If you `MatMul` two tensors that implement a custom tensor, the passed `prealloc` tensor doesn't use the same engine that those two tensors used.  Is there any way to change the engine or specify that the `prealloc` tensor should use a certain engine?  I implemented a copy to change the engine which basically copies the backing data and makes a new tensor using my engine but that seems inefficient.

Thanks a lot for your support!

**Comment by chewxy** [comment]
I'm not entirely sure what you meant. I see two possible interpretations of your question:

# Interpretation 1 #
Did you mean when doing `tensor.MatMul(a, b)`, the result doesn't have the same engine as `a` or `b` ? If so, that's indeed a missing feature, and if you want, feel free to make a pull request. The line to add is this:

```
retVal.e = t.e
```

This line needs to be added: 

* [here](https://github.com/gorgonia/tensor/blob/master/dense_linalg.go#L89)
* [here](https://github.com/gorgonia/tensor/blob/master/dense_linalg.go#L135)
* [here](https://github.com/gorgonia/tensor/blob/master/dense_linalg.go#L172)

If you don't want to make a PR, it'll be in the next version of Gorgonia (v0.9.0), which is at this point seemingly permanently 2 weeks away.

# Interpretation 2 #

You were trying to do `tensor.MatMul(a, b, tensor.WithPrealloc(prealloc))`. Of which, the solution is to simply do this: `tensor.WithEngine(MyEngine{})(prealloc)` which changes the engine for `prealloc`

**Comment by chewxy** [comment]
all good?

**Comment by bendecoste** [comment]
yes thanks!
