### ISSUE TITLE
Embed `AP` instead of `*AP` 

### ISSUE THREAD

**Issue by chewxy** [gorgonia/tensor#4]
_From @chewxy on August 30, 2017 23:31_

Was doing an allocation analysis to improve the package in general. Things can be improved very slightly by embedding `AP` instead of `*AP` in `*CS` and `*Dense`

_Copied from original issue: chewxy/gorgonia#145_

**Comment by docmerlin** [comment]
I'm looking at this issue.

**Comment by docmerlin** [comment]
I'm looking at this issue.

**Comment by chewxy** [comment]
mind accepting the invite so I can actually list you as the assignee? Github is weird af

**Comment by docmerlin** [comment]
Ok, accepted.
