### ISSUE TITLE
Casting between data types

### ISSUE THREAD

**Issue by cli99** [gorgonia/tensor#40]
Is there a way to cast a dense matrix between different data types. The use case is that I have data that's a uint8 but I want to represent it as a dense matrix of float32.

thank you

**Comment by chewxy** [comment]
Just so our terminology here, my understanding of conversion and casting is as such:

* **Casting**: read the same amount of bit as a different type
* **Conversion**: create data of a different type, representing the same values.

**Example:**

```
a := float32(1.0)
```

`a` is a  `float32`. I can cast it as 

* 4 `uint8`s: `[0 0 128 63]`
* 4 `int8`:s `[0 0 -128 63]`
* 2 `int16`s : `[0 16256]`
* 2 `uint16`s: `[0 16256]`

This, I think should give you some sense of danger when it comes to casting. If you have a slice of `uint8`. casting it into a dense matrix of `float32` will definitely cause some weirdness unless you are very careful about it.

For example, a (2,2) `byte` matrix would not be able to be safely cast into a (2,2)  `float32` matrix. The best it can do is to cast it into a (1,1) matrix. 

More common however, is **conversion**:

```
a := tensor.New(tensor.WithShape(2,2), tensor.WithBacking([]byte(1,2,3,4}) 

backing := a.Data().([]byte)
backing2 := make([]float32, len(backing)
for i := range backing {
    backing2[i] = float32(backing[i])
}
a2 = tensor.New(tensor.WithShape(a.Shape()...), tensor.WithBacking(backing2))
```

----

As you can see, there are different meanings as to what you really want to do. 


The difference between conversion and casting is that conversion requires allocation of new memory, while casting does not. It's often unclear what the end user wants to do when they say "casting". 

Hence the tensor package doesn't actually provide such functionalities - in the future, we will definitely add a `Convert` function, but the API at this point is not clear yet.

**Comment by cli99** [comment]
I would like to do type conversion. The above code works. Is it possible to do it with ```func (*Dense) Apply```?

**Comment by chewxy** [comment]
Nope. The main reason is a `*tensor.Dense` is a fixed size array. A (2,2) `byte` matrix for example, takes 4 bytes. 4 bytes is enough space for 1 `float32` only. Hence you have to do what I did above - allocate new memory. `Apply` works within the fixed memory size.
